echo "const PlotData = {};" > data/index.js
echo "const Features = {};" > data/galaxyFeatures.js
echo "PlotData.redshift = $(cat data/redshift.json);" >> data/index.js
echo "PlotData.bptclass = $(cat data/bptclass.json);" >> data/index.js
echo "PlotData.petroR90 = $(cat data/petroR90.json);" >> data/index.js
echo "PlotData.lgm_tot_p50 = $(cat data/lgm_tot_p50.json);" >> data/index.js
echo "PlotData.spectral = $(cat data/spectral.json);" >> data/index.js
echo "const PointMetadata = $(cat data/metadata.json);" >> data/index.js
echo "Features.redshift_seed32_fold1 = {};" >> data/galaxyFeatures.js
echo "Features.redshift_seed32_fold1.redshift = $(cat data/learned-features-seed32-fold-1-20_redshift.json);" >> data/galaxyFeatures.js
echo "Features.featureOptions = ['redshift', 'deredened petro Magnitudes'];" >> data/galaxyFeatures.js
